@echo off
echo Starting Stock Scanner Server...
cd /d "%~dp0"
start "StockScannerServer" cmd /k "python app.py"
echo Waiting for server to start...
ping 127.0.0.1 -n 4 > nul
echo Opening browser...
start http://127.0.0.1:8000
